### ISSUE TITLE
pygccxml.parser.source_reader.gccxml_runtime_error_t: Error occured while running GCC-XML: 

### ISSUE THREAD

**Issue by sherry0009** [gccxml/pygccxml#18]
Hi, I am trying to make a python-bindings of a motion planning library. 
The fllowing error appears:

INFO Parsing source file "bindings/util.h" ... 
INFO gccxml cmd: /usr/local/bin/gccxml  -I"." -I"/home/sherry/Workspace/batch-infromed-trees/ompl/src" -I"/home/sherry/Workspace/batch-infromed-trees/src" -I"/usr/include/python2.7" -I"/usr/include" -I"/usr/include/assimp" -I"/usr/local/include/eigen3"   "bindings/util.h" -fxml="/tmp/tmpMlywrt.xml"
In file included from /usr/local/include/eigen3/Eigen/Core:265,
                 from bindings/util.h:120:
/usr/local/include/eigen3/Eigen/src/Core/arch/SSE/Complex.h: In function 'Packet Eigen::internal::pset1(const typename Eigen::internal::unpacket_traits<T>::type&) [with Packet = Eigen::internal::Packet2cf]':
/usr/local/include/eigen3/Eigen/src/Core/arch/SSE/Complex.h:95: error: #pragma GCC diagnostic not allowed inside functions
/usr/local/include/eigen3/Eigen/src/Core/arch/SSE/Complex.h:96: error: #pragma GCC diagnostic not allowed inside functions
/usr/local/include/eigen3/Eigen/src/Core/arch/SSE/Complex.h:98: error: #pragma GCC diagnostic not allowed inside functions
Traceback (most recent call last):
  File "/home/sherry/Workspace/batch-infromed-trees/ompl/py-bindings/generate_bindings.py", line 735, in <module>
    globals()['ompl_'+module+'_generator_t']()
  File "/home/sherry/Workspace/batch-infromed-trees/ompl/py-bindings/generate_bindings.py", line 671, in __init__
    code_generator_t.__init__(self, 'util', None, replacement, 1)
  File "/home/sherry/Workspace/batch-infromed-trees/ompl/py-bindings/ompl/bindings_generator.py", line 148, in __init__
    indexing_suite_version = indexing_suite_version )
  File "/usr/local/lib/python2.7/dist-packages/pyplusplus/module_builder/boost_python_builder.py", line 95, in __init__
    , indexing_suite_version)
  File "/usr/local/lib/python2.7/dist-packages/pyplusplus/module_builder/boost_python_builder.py", line 138, in __parse_declarations
    decls = reader.read_files( files, compilation_mode )
  File "build/bdist.linux-x86_64/egg/pygccxml/parser/project_reader.py", line 250, in read_files
  File "build/bdist.linux-x86_64/egg/pygccxml/parser/project_reader.py", line 279, in __parse_file_by_file
  File "build/bdist.linux-x86_64/egg/pygccxml/parser/source_reader.py", line 226, in read_file
  File "build/bdist.linux-x86_64/egg/pygccxml/parser/source_reader.py", line 260, in read_gccxml_file
pygccxml.parser.source_reader.gccxml_runtime_error_t: Error occured while running GCC-XML: 

Please tell me the cause of error. Is the version of gcc or the version of gccxml ? Or the version of system?
(64bit Ubuntu 14.04,  gcc 4.8.2 ,  gccxml and pygccxml are the latest version) 
I try to change the version of gcc, like 4.6.3, 4.6.4, 4.7 and 4.9. But, it still doesn't  work.
ps: The only successful attempt is on 32bit Ubuntu 12.04 ，and the gcc version is 4.6.3.   
Please tell me how can I solve it on Ubuntu 14.04.
Regards!

**Comment by iMichka** [comment]
Ping @mamoll

**Comment by mamoll** [comment]
It does sound more like a gccxml issue. The bug tracker for gccxml is here: http://www.gccxml.org/Bug/my_view_page.php

**Comment by iMichka** [comment]
Hi

I know this bug has been open for long. We may now have a solution, if you are still interested. GCCXML has been replaced by CastXML. pygccxml 1.7.0 has just been released with CastXML support.

You can find the changelog and some explanations here: http://pygccxml.readthedocs.org/en/develop/history.html

Sorry for the delay, it took longer than expected.

I'll close this bug, please reopen a new one if you have any trouble with CastXML or the new version of pygccxml.
