### ISSUE TITLE
Exception: Demangled name is not available with CastXML.

### ISSUE THREAD

**Issue by dodgyville** [gccxml/pygccxml#93]
Hi, great project!

On ubuntu 16.10 and python3 using castxml (gccxml no longer compiles) I can't generate bindings from a header file due to this error:
```

INFO Parsing source file "my-module.h" ... 
Traceback (most recent call last):
  File "generate.py", line 25, in <module>
    my_module_gen()
  File "generate.py", line 18, in my_module_gen
    module = module_parser.parse([f])

  File "/usr/local/lib/python3.5/dist-packages/pybindgen/gccxmlparser.py", line 602, in parse
    self.scan_functions()

  File "/usr/local/lib/python3.5/dist-packages/pybindgen/gccxmlparser.py", line 2077, in scan_functions
    self._scan_namespace_functions(self.module, self.module_namespace)

  File "/usr/local/lib/python3.5/dist-packages/pybindgen/gccxmlparser.py", line 2216, in _scan_namespace_functions
    if templates.is_instantiation(fun.demangled_name):

  File "/usr/lib/python3/dist-packages/pygccxml/declarations/calldef.py", line 396, in demangled_name
    raise Exception("Demangled name is not available with CastXML.")
Exception: Demangled name is not available with CastXML.
```

my-module.h contains the following line from the tutorial:

`
void MyModuleDoAction (void);
`

and my call to the parser is:

 ```
   f = "my-module.h"

    module_parser = ModuleParser('a1', '::')

    module = module_parser.parse([f])

    module.add_include('"%s"'%f)

```

I also had to manually force
`        self.gccxml_config.xml_generator_path = "/usr/bin/castxml" 
`

As it looks like find_xml_generator is not called anywhere in pygccxml.

**Comment by BenNewton** [comment]
Did you ever figure this out?

**Comment by iMichka** [comment]
Hi. Sorry I did not answer before.
The bug is not in pygccxml, but in `pybindgen`. They maybe fixed it since then?

You can not access `fun.demangled_name`, this is not available anymore with the newer version of pygccxml and castxml. You could try using `fun.name` instead in `pybindgen`.
